apiVersion: v1
kind: Pod
metadata:
  name: policy-installer
  namespace: selinux-policy-helper-operator
spec:
  containers:
  - name: policy-installer
    image: quay.io/jaosorior/selinux-k8s:latest
    command: ["/bin/sh"]
    args: ["-c", "semodule -vi /tmp/policy/*.cil /usr/share/udica/templates/*cil"] 
    securityContext:
      privileged: true
    volumeMounts:
    - name: fsselinux
      mountPath: /sys/fs/selinux
    - name: etcselinux
      mountPath: /etc/selinux
    - name: varlibselinux
      mountPath: /var/lib/selinux
    - name: policy-volume
      mountPath: /tmp/policy
  restartPolicy: Never
  nodeName: NODE_NAME
  volumes:
  - name: fsselinux
    hostPath:
      path: /sys/fs/selinux
      type: Directory
  - name: etcselinux
    hostPath:
      path: /etc/selinux
      type: Directory
  - name: varlibselinux
    hostPath:
      path: /var/lib/selinux
      type: Directory
  - name: policy-volume
    configMap:
      name: policy-for-errorlogger-errorlogger
  serviceAccount: selinux-policy-helper-operator
