apiVersion: apps/v1
kind: Deployment
metadata:
  name: selinux-policy-helper-operator
  namespace: openshift-selinux-policy-helper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: selinux-policy-helper-operator
  template:
    metadata:
      labels:
        name: selinux-policy-helper-operator
    spec:
      serviceAccountName: selinux-policy-helper-operator
      containers:
        - name: selinux-policy-helper-operator
          image: "quay.io/jaosorior/selinux-policy-helper-operator"
          command:
          - selinux-policy-helper-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "selinux-policy-helper-operator"
